name: Metrics
on:
  # Schedule updates (each hour)
  schedule: [{cron: "0 * * * *"}]
  # Lines below let you run workflow manually and on each commit (optional)
  workflow_dispatch:
  push: {branches: ["main"]}

jobs:
  metrics:
    runs-on: ubuntu-latest
    steps:
      - uses: lowlighter/metrics@v3.32
        with:
          filename: metrics.classic.svg
          token: ${{ secrets.METRICS_OVERVIEW_TOKEN }}
          base: header
          plugin_lines: yes
